#include "Type.h"
#include "GL.h"
#include "R.h"

#define ARRAY_SIZE(a)   sizeof(a)/sizeof(a[0])

static const char *resTable[]={
    "btn_aim_cursor",
    "btn_back_n",
    "btn_back",
    "btn_cancel",
    "btn_cursor",
    "btn_down",
    "btn_help",
    "btn_honor",
    "btn_menu",
    "btn_next",
    "btn_off",
    "btn_ok",
    "btn_on",
    "btn_options",
    "btn_pause",
    "btn_play_x2",
    "btn_play",
    "btn_replay",
    "btn_save",
    "btn_stop",
    "btn_up",
    "btn_video",
    "bullet_0",
    "bullet_1",
    "bullet_2",
    "bullet_mg_0",
    "bullet_mg_1",
    "bullet_mg_2",
    "bullet_mg_3",
    "enemy_gb_0",
    "enemy_gb_1",
    "enemy_gb_2",
    "enemy_gb_3",
    "enemy_qc_0",
    "enemy_qc_1",
    "enemy_qc_2",
    "enemy_qc_3",
    "enemy_sb_0",
    "enemy_sb_1",
    "enemy_sb_2",
    "enemy_sb_3",
    "enemy_tk_0",
    "enemy_tk_1",
    "enemy_tk_2",
    "enemy_tk_3",
    "enemy_zj_0",
    "enemy_zj_1",
    "enemy_zj_2",
    "enemy_zj_3",
    "entrance_l",
    "entrance_r",
    "entrance_u",
    "entrance_d",
    "exp_0",
    "exp_1",
    "exp_2",
    "exp_3_0_0",
    "exp_3_0_1",
    "exp_3_0_2",
    "exp_3_1_0",
    "exp_3_1_1",
    "exp_3_1_2",
    "exp_3_2_0",
    "exp_3_2_1",
    "exp_3_2_2",
    "exp_4_0_0",
    "exp_4_0_1",
    "exp_4_0_2",
    "exp_4_1_0",
    "exp_4_1_1",
    "exp_4_1_2",
    "exp_4_2_0",
    "exp_4_2_1",
    "exp_4_2_2",
    "exp_5_0_0",
    "exp_5_0_1",
    "exp_5_0_2",
    "exp_5_1_0",
    "exp_5_1_1",
    "exp_5_1_2",
    "exp_5_2_0",
    "exp_5_2_1",
    "exp_5_2_2",
    "explose_0",
    "explose_1",
    "explose_2",
    "explose_3",
    "explose_4",
    "explose_5",
    "explose_6",
    "fish",
    "honor_star_b_s",
    "honor_star_b",
    "honor_star_e_s",
    "honor_star_e",
    "honor_star",
    "house_destory_2",
    "house_destory_3",
    "house_destory_big",
    "house",
    "icon_coin",
    "icon_ding",
    "icon_large_shadow",
    "lock",
    "logo_mine",
    "logo_war",
    "logo",
    "map_forest_s",
    "map_forest",
    "map_house_s",
    "map_land_danger",
    "map_land_s",
    "map_land",
    "map_road_danger",
    "map_road_s",
    "map_road",
    "map_water_danger",
    "map_water_s",
    "map_water",
    "mine_ft",
    "mine_ft2",
    "mine_fz",
    "mine_fz2",
    "mine_lb_r2",
    "mine_lb",
    "mine_lb2",
    "mine_pt",
    "mine_pt2",
    "mine_tl",
    "mine_tl2",
    "minegun_1_1",
    "minegun_1_2",
    "minegun_2_1",
    "minegun_2_2",
    "minegun",
    "n_0",
    "n_1",
    "n_2",
    "n_3",
    "n_4",
    "n_5",
    "n_6",
    "n_7",
    "n_8",
    "n_9",
    "n_s",
    "n_d",
    "new_record",
    "plant_planting_dry",
    "plant_planting_mature",
    "plant_planting",
    "plant_seed",
    "plant_seedling_dry",
    "plant_seedling",
    "star_empty",
    "star_house",
    "star_landmine",
    "star_plant",
    "star",
    "tool_aim",
    "tool_explose",
    "tool_knife",
    "tool_remote",
    "tool_seed",
    "tool_shovel",
    "toolbar_knife",
    "toolbar_mine_ft",
    "toolbar_mine_fz",
    "toolbar_mine_lb",
    "toolbar_mine_pt",
    "toolbar_mine_tl",
    "toolbar_minegun",
    "toolbar_seed",
};

static const char * prefixTable[]={
    "i6p_"  , //DEV_3X_IPHONE6P,
    "i6_"   , //DEV_2X_IPHONE6,
    "i5_"   , //DEV_2X_IPHONE5,
    "i4_"   , //DEV_2X_IPHONE4,
    ""      , //DEV_1X_IPAD,
    ""      , //DEV_2X_IPAD,
};

static const char * postfixTable[]={
    "@3x"  	, //DEV_3X_IPHONE6P,
    "@2x"   , //DEV_2X_IPHONE6,
    "@2x"   , //DEV_2X_IPHONE5,
    "@2x"   , //DEV_2X_IPHONE4,
    ""      , //DEV_1X_IPAD,
    "@2x"   , //DEV_2X_IPAD,
};

void R_load(int type)
{
    char fileName[2048];
	int i;

	GL.allocResArray(ARRAY_SIZE(resTable));
    
    for(i = 0; i < ARRAY_SIZE(resTable); i++){
        sprintf(fileName, ".\\res\\%s%s%s.png" , prefixTable[type], resTable[i], postfixTable[type]);
        _LOGD("Res", "%s\n", fileName);
        GL.addImage(i, fileName);
    }

	GL.loadFont(".\\res\\font70.png");
}

void R_free(void)
{
	GL.freeResArray();
}
